version: "3.1"

services:

  database:
    image: mongo:5
    restart: unless-stopped
    networks:
      - backend-network
    volumes:
      - type: bind
        source: ./database
        target: /data/db
        
  backend:
    build: backend/
    restart: unless-stopped
    networks: 
      - backend-network
    depends_on: 
      - postgres
    ports:
      - '5000:5000'
  
networks:
  backend-network:
